### ISSUE TITLE
Implement Blog Feature 

### ISSUE THREAD

**Issue by rcarteraz** [meshtastic/Meshtastic#1082]
Opening this as placeholder for now based on the discussion in #1053 about implementing the blog feature.

**Comment by tekstrand** [comment]
Do you have a plan on this issue, maybe expanding the details a bit more and then asking for feedback from the larger contributor community?

**Comment by tekstrand** [comment]
Starting to think through contribution guidelines. A few thoughts/questions

1. What are acceptable topics? Maybe better asked, what are unacceptable topics? (My concern is that folks will try to use this as self promotion rather than truly helping the community)
2. Do we want to be prescriptive about about tone/style(e.g. professional, informational, casual) or is this anything goes? (I think we should be prescriptive. Informational/professional.
3. Can the author post this content in multiple places, or is there an expectation that it can only be posted here? (I think no, expectation is that it is only posted here)
4. Do authors maintain rights to their content? (I think no)
5. Does our current [code of conduct](https://meshtastic.org/docs/legal/conduct/) support this new content type sufficiently? (I think it does)

**Comment by tekstrand** [comment]
Great point on frequency. I think 1-2 times per month is acceptable, personally. If someone can truly produce quality content that often, why not let them? If it's just AI produced garbage, I think the review process would capture it.

Agree with all of your other points and agree on the posting multiple places.

Other things I believe it is important to have defined

- purpose
- submission process(same as docs, but still)
- formatting/style
  - length guidelines/recommendations (we don't want books, we also don't want 2 paragraphs, I think.
  - heading/image/media instructions
- author section acceptable content (you sort of covered this in the self promo thing, but we might need to be more specific on other parts, too)

**Comment by tekstrand** [comment]
First pass at contribution guidelines linked

**Comment by ianmcorvidae** [comment]
The only addition I think I'd suggest is that we should encourage links to whatever posted a given thing originally (whether that's us or somewhere else), with the possible exception of folks republishing things from their personal blogs (which they can instead link in their bio). I think it's helpful for folks to follow a link to hackaday or similar if we're getting it second, and it's definitely good for us if something on hackaday has a link back to us, too.
