### ISSUE TITLE
nRF52 Driver Install Clarification

### ISSUE THREAD

**Issue by pdxlocations** [meshtastic/meshtastic#696]
On the nRF Flashing Firmware page it is stated "No driver or software install is required on any platform."
https://meshtastic.org/docs/getting-started/flashing-firmware/nrf52/

However, there are still instructions on installing drivers for Windows and Linux on the Serial Drivers pages.
https://meshtastic.org/docs/getting-started#install-serial-drivers
https://meshtastic.org/docs/getting-started/serial-drivers/nrf52

Do any platforms require serial drivers for nRF devices to load firmware or perform any other function?

**Comment by garthvh** [comment]
There are certainly a lot of linux exceptions, it is not in linux mint for example.

**Comment by markbirss** [comment]
@pdxlocations 

No serial driver is required to be able to use UF2

https://github.com/adafruit/Adafruit_nRF52_Bootloader
UF2 is an easy-to-use bootloader that appears as a flash drive. You can just copy .uf2-format application images to the flash drive to load new firmware. See https://github.com/Microsoft/uf2 for more information.

**Comment by markbirss** [comment]
@pdxlocations 

However a serial driver would be needed for say an ESP32-S3 in order to install UF2 support as it is done via esptool which requires serial port access

https://esp32s3.com/install_uf2.html

With NRF52 you would use the SWDIO interface with a DapLink/ST-Link/J-Link/etc using the SWDIO and SWDCLK interface pins
