### ISSUE TITLE
Configure versioning for 3.0

### ISSUE THREAD

**Issue by rcarteraz** [meshtastic/Meshtastic#828]
With 3.0 on the horizon, we need to configure versioning for the docs. 

https://docusaurus.io/docs/versioning

**Comment by pdxlocations** [comment]
I wasn't around for the 2.0 switch so I don't know how versioning works but I'm looking forward to learning!

**Comment by pdxlocations** [comment]
> > I wasn't around for the 2.0 switch so I don't know how versioning works but I'm looking forward to learning!
> 
> Added a link. Allows us to maintain docs for different versions.

Oh fun.  That page was last updated 3 days ago by our friend slorber.  I'm guessing he added the motivational comment, "Most of the time, you don't need versioning as it will just increase your build time, and introduce complexity to your codebase."

Was versioning used for the transition to 2.0? 

Is the point of this:
A. so users can navigate  2.x docs if they haven't updated to 3.x?
and/or
B. so we can have a series of docs ready to release when 3.0 is released?

If A == true, will our intra-site linking break for previous versions since directory structure will change to  "/docs/2.0.0/about" for example?

Will there be enough changes to warrant maintaining two versions while there is overlap?

As our guide slorber says, "Versioning is best suited for websites with high-traffic and rapid changes to documentation between versions. If your documentation rarely changes, don't add versioning to your documentation."

Don't get me wrong, I'm not opposed to versioning, just trying to wrap my head around it and Slorber does not sell the feature well.  Thanks!

**Comment by jfirwin** [comment]
One of our biggest complaints on the 1.0 to 2.0 transition was our docs. We immediately switched things over to 2.0, before it was live and we lost some momentum because 1.0/2.0 was a huge breaking change. I've been away so I don't know what we plan for 3.0. But I'm happy to help set up the versioning. Its definitely an important fix.

I think https://docusaurus.io/docs/versioning#recommended-practices addresses some of the questions that @pdxlocations is asking. I think the point will be `A` in your comment.

`B` should probably be implemented by working the docs on a separate branch that isn't pushed live until 3.0 is released.

**Comment by jfirwin** [comment]
Hindsight is 20/20, and one of the biggest fails we made was not creating a branch. It would have allowed us to move small grammatical/minor fixes from the main docs into our 2.0 docs while working on 2.0. Hopefully we don't have major structural changes, but I think a version for each major release is plenty. Maybe minor release versioning if new features are added.

**Comment by pdxlocations** [comment]
> I think https://docusaurus.io/docs/versioning#recommended-practices addresses some of the questions that @pdxlocations is asking.

This is the part that made me think we'd have a bit of work to do to clean up our current links.  Something I'm happy to work on but something to add to the list, yah?

> Hindsight is 20/20, and one of the biggest fails we made was not creating a branch. It would have allowed us to move small grammatical/minor fixes from the main docs into our 2.0 docs while working on 2.0. Hopefully we don't have major structural changes, but I think a version for each major release is plenty. Maybe minor release versioning if new features are added.

So creating a 3.0 branch sort of mitigates having to make any small fixes twice?  I'm still new to git so moving commits around branches is something I'll have learn.

I'm interested in seeing all the ideas for the V3 firmware as the project gets built.  I'm having trouble imagining how many changes the docs will need beyond a splash page and a few "v3 and above" notes.


> Your first mistake is taking anything slorber says as something serious.

True, but you posted the link, so...
